---

- name: set php tunables
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp="{{ item.regexp }}"
              line"={{ item.line }}"
  with_items:
  - { regexp: '^;?post_max_size', line: 'post_max_size = 32M' }
  - { regexp: '^;?opcache.validate_timestamps', line: 'opcache.validate_timestamps=0' } 
  notify: restart php5-fpm
